apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: logdb
  name: logdb
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app.kubernetes.io/name: logdb
