{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
{{- if eq .Values.global.settings.curiefense_es_forwarder "logstash" }}
{{- if .Values.global.enable.logstash }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: {{ .Release.Namespace }}
data:
  logstash.conf: |-
    input {
        http {
            port => 5001
        }
    }
    output {
        elasticsearch {
            hosts => "{{ .Values.global.settings.curiefense_es_hosts }}"
            index => "${CURIEFENSE_ES_INDEX_NAME:curieaccesslog}"
            # Action create is required for data streams which are,
            # by definition, an append only type of index. Only
            # a create op_type is supported when using data streams.
            # This works fine under environments that don't use
            # data streams.
            action => "create"
        }
    }
{{- end }}
{{- end }}
{{- end }}
