apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: curielogger
  name: curielogger
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: curielogger
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curielogger
    spec:
      containers:
      - name: curielogger
        env:
        - name: CURIELOGGER_METRICS_PROMETHEUS_ENABLED
          value: "{{ .Values.global.settings.curiefense_metrics_prometheus_enabled }}"
{{- if eq .Values.global.settings.curiefense_logdb_type "elasticsearch" }}
        - name: ELASTICSEARCH_URL
          value: "{{ .Values.global.settings.curiefense_es_hosts }}"
{{- if eq .Values.global.settings.curiefense_es_forwarder "logstash" }}
        - name: CURIELOGGER_OUTPUTS_LOGSTASH_ENABLED
          value: "true"
        - name: CURIELOGGER_OUTPUTS_LOGSTASH_URL
          value: "{{ .Values.global.settings.curiefense_logstash_url }}"
{{- else }}
        - name: CURIELOGGER_USES_FLUENTD
          value: "true"
        - name: CURIELOGGER_FLUENTD_URL
          value: "{{ .Values.global.settings.curiefense_fluentd_url }}"
        - name: USE_DATA_STREAMS
          value: "false"
{{- end }}
        - name: CURIELOGGER_KIBANA_URL
          value: "{{ .Values.global.settings.curiefense_kibana_url }}"
{{- if .Values.global.enable.kibana }}
        - name: CURIELOGGER_INITIALIZE_KIBANA_INDEX
          value: "true"
{{- end }}
{{- end }}
        {{ if regexMatch ".*/.*:" .Values.global.images.curielogger }}
        {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
        image: {{ .Values.global.images.curielogger }}
        {{ else }}
        image: {{ .Values.global.images.curielogger }}:{{ .Values.global.settings.docker_tag }}
        {{ end }}
        ports:
        - containerPort: 9001
          name: logger-grpc
        - containerPort: 2112
          name: logger-p8s
        livenessProbe:
          tcpSocket:
            port: logger-grpc
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        resources:
          limits:
            memory: "500Mi"
            cpu: "900m"
          requests:
            memory: "20Mi"
            cpu: {{ .Values.global.requests.cpu.curielogger }}
      restartPolicy: Always
      serviceAccountName: ""
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
