apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
  name: redis
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
