{{- $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if $gateway.waf.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: curiefense-lua-filter
  namespace: {{ .Release.Namespace }}
spec:
  workloadSelector:
    labels:
      curiefense: "enabled"
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        portNumber: 80
    patch:
      operation: INSERT_BEFORE
      value: # lua filter specification
       name: envoy.lua
       config:
         inlineCode: |
            local session = require "lua.session"
            function envoy_on_request(handle)
              session.inspect(handle)
            end
{{- end }}
