{
 "title": "Traffic Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Blocked  vs Passed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[1m])) by (blocked)",
     "legendFormat": "{{ blocked }}"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[1m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  },
  {
   "title": "HTTP Origin Status",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[1m])) by (origin_status_code)",
     "legendFormat": "{{ origin_status_code }}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[1m])) by (method)",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "description": "A number of requests per minute",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(curiemetric_http_request_total[1m])",
     "legendFormat": "1m"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(curiemetric_request_bytes[1m])",
     "legendFormat": "In"
    },
    {
     "expr": "rate(curiemetric_response_bytes[1m])",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}