{
 "title": "Traffic overview (demo)",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<font size= \"10\"> <center>  Reblaze traffic overview  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "hits",
   "type": "stat",
   "description": "total number of requests   total ",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expr": "sum(rate(hits_total[10s]))" }
   ]
  },
  {
   "title": "countries",
   "type": "stat",
   "description": "total number of unique countries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(top_active_country_total) by (country))"
    }
   ]
  },
  {
   "title": "ASNs",
   "type": "stat",
   "description": "total number of unique countries ASNs",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(top_passed_asn_total) by (asn))"
    }
   ]
  },
  {
   "title": "HTTP status class (2xx, 3xx, 4xx, 5xx)",
   "type": "piechart",
   "description": "number of requests grouped by http status class",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum by (code_class) (irate(status_classes_total[10s]))",
     "legendFormat": "{{code_class}}xx"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(irate(hits_total[30s]))", "legendFormat": "hits" },
    {
     "expr": "sum(irate(hits_total[30s])) - sum(irate(passed_total[30s]))",
     "legendFormat": "blocked"
    },
    { "expr": "sum(irate(passed_total[30s]))", "legendFormat": "passed" },
    {
     "expr": "sum(irate(reported_total[30s]))",
     "legendFormat": "report"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " round(sum by (method) (irate(methods_total[10s]))) ",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Statuses",
   "type": "timeseries",
   "description": "total number of requests  grouped by http statuses",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum by (code) (irate(status_total[10s])) ",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Organisations (ASN)",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (asn) (irate(top_active_asn_total[10s]))",
     "legendFormat": "active: {{asn}}"
    },
    {
     "expr": "(sum by (asn) (irate(top_passed_asn_total[10s]))) ",
     "legendFormat": "passed: {{asn}}"
    },
    {
     "expr": "(sum by (asn) (irate(top_reported_asn_total[10s])))",
     "legendFormat": "report: {{asn}}"
    }
   ]
  },
  {
   "title": "Countries",
   "type": "timeseries",
   "description": "number of  requests per country ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum by (country) (irate(top_active_country_total[10s])))",
     "legendFormat": "active: {{country}}"
    },
    {
     "expr": "round((sum by (country) (irate(top_passed_country_total[10s]))) )",
     "legendFormat": "passed: {{country}}"
    },
    {
     "expr": "round((sum by (country) (irate(top_reported_country_total[10s]))))",
     "legendFormat": "report: {{country}}"
    }
   ]
  },
  {
   "type": "text",
   "description": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<font size= \"4\"> <center>  Unique metrics  </center></font> "
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Unique Reblaze Sessions ",
   "type": "timeseries",
   "description": "number of unique sessions",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum((unique_passed_session))) ",
     "legendFormat": "unique sessions passed"
    },
    { "expr": "round(sum(unique_session)) ", "legendFormat": "unique sessions total" }
   ]
  },
  {
   "title": "Unique URIs",
   "type": "timeseries",
   "description": "number of unique URIs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "round(sum(unique_passed_uri))", "legendFormat": "unique URIs passed" },
    { "expr": "round(sum(unique_uri))", "legendFormat": "unique URIs total" }
   ]
  },
  {
   "title": "Unique Countries",
   "type": "timeseries",
   "description": "total number of requests  grouped by http method",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(unique_passed_country))",
     "legendFormat": "unique Countries passed"
    },
    { "expr": "round(sum(unique_country))", "legendFormat": "unique Countries total" }
   ]
  },
  {
   "title": "Unique IPs",
   "type": "timeseries",
   "description": "number of unique  IPs",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "round(sum(unique_passed_ip))", "legendFormat": "unique IPs passed" },
    { "expr": "round(sum(unique_ip))", "legendFormat": "unique IPs total" }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(processing_time_average) by (proxy)",
     "legendFormat": "processing time average"
    },
    {
     "expr": " sum(processing_time_max) by (proxy)",
     "legendFormat": "bytes sent max"
    },
    {
     "expr": "sum(processing_time_min) by (proxy)",
     "legendFormat": "processing time min"
    }
   ]
  },
  {
   "title": "Bytes sent",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " sum(bytes_sent_average) by (proxy)",
     "legendFormat": "bytes sent average"
    },
    {
     "expr": " sum(bytes_sent_max) by (proxy)",
     "legendFormat": "bytes sent max"
    },
    { "expr": "sum(bytes_sent_min) by (proxy)", "legendFormat": "bytes sent min" }
   ]
  },
  {
   "title": "Unique User Agent",
   "type": "timeseries",
   "description": "number of user agents ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(unique_passed_user_agent))",
     "legendFormat": "unique user agents  passed"
    },
    { "expr": "round(sum(unique_user_agent))", "legendFormat": "unique user agents total" }
   ]
  }
 ]
}