apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: curielogserver
  name: curielogserver
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: curielogserver
