apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: curielogserver
  name: curielogserver
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: curielogserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: curielogserver
    spec:
      containers:
      - name: curielogserver-nginx
        {{ if regexMatch ".*/.*:" .Values.global.images.curielogserver }}
        {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
        image: {{ .Values.global.images.curielogserver }}
        {{ else }}
        image: {{ .Values.global.images.curielogserver }}:{{ .Values.global.settings.docker_tag }}
        {{ end }}
        ports:
        - containerPort: 80
          name: logserver-http
        livenessProbe:
          httpGet:
            path: /api/v1/
            port: logserver-http
        volumeMounts:
        - mountPath: /uwsgi
          name: uwsgi-socket
        command: ["/usr/bin/dumb-init", "/bin/bash", "/init/start_nginx.sh"]
      - name: curielogserver-uwsgi
        env:
        - name: CURIELOGSERVER_DBHOST
          value: {{ .Values.global.settings.curiefense_db_hostname }}
        - name: CURIELOGSERVER_DBUSER
          valueFrom:
            secretKeyRef:
              name: curiefense-db-readonly-credentials
              key: username
        - name: CURIELOGSERVER_DBPASSWORD
          valueFrom:
            secretKeyRef:
              name: curiefense-db-readonly-credentials
              key: password
        {{ if regexMatch ".*/.*:" .Values.global.images.curielogserver }}
        {{/* The image name contains a version tag (e.g. for tests), do not append docker_tag */}}
        image: {{ .Values.global.images.curielogserver }}
        {{ else }}
        image: {{ .Values.global.images.curielogserver }}:{{ .Values.global.settings.docker_tag }}
        {{ end }}
        volumeMounts:
        - mountPath: /uwsgi
          name: uwsgi-socket
        command: ["/usr/bin/dumb-init", "/bin/bash", "/init/start_uwsgi.sh"]
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: uwsgi-socket
        emptydir: {}
{{- if .Values.global.tolerations }}
      tolerations:
{{ toYaml .Values.global.tolerations | indent 8 }}
{{- end }}
