{
 "title": "Traffic Overview",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[5m])) by (status_class)",
     "legendFormat": "{{ status_class }}"
    }
   ]
  },
  {
   "title": "Requests Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(curiemetric_request_bytes[5m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Requests Bandwidth",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(curiemetric_request_bytes[5m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Blocked  vs Passed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[5m])) by (blocked)"
    }
   ]
  },
  {
   "title": "HTTP Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(curiemetric_session_details_total[5m])) by (status_code)",
     "legendFormat": "{{ status_code }}"
    }
   ]
  }
 ]
}