name: Run e2e tests on docker-compose

on: [push, pull_request]

jobs:
  e2e-docker-compose:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run tests
        run: |
            export BASEDIR=$(git rev-parse --show-toplevel)
            export VERSION=$(git rev-parse --short=12 HEAD)

            # Deploy all services: istio, curiefense, and echoserver (test app)
            deploy/deploy-ci-compose.sh

            echo "-- Install curieconfctl --"

            python3 -m venv "$BASEDIR/venv"
            source "$BASEDIR/venv/bin/activate"
            pip install -U requests pytest pytest-html wheel

            pushd "curiefense/curieconf/utils"
            pip install -e .
            popd

            pushd "curiefense/curieconf/client"
            pip install -e .
            popd

            echo "-- Run e2e tests --"
            pushd e2e
            IP=127.0.0.1
            pytest --log-level INFO --base-protected-url http://$IP:30081 --base-conf-url http://$IP:30000/api/v1/ --base-ui-url http://$IP:30080 --elasticsearch-url http://$IP:9200/ --junit-xml pytest.xml -k 'not (test_ipv4 or test_wafsig or test_ratelimit_scope_ipv4_include or test_ratelimit_scope_ipv4_exclude or test_ratelimit_scope_country_include or test_ratelimit_scope_country_exclude or test_ratelimit_scope_company_include or test_ratelimit_scope_company_exclude or test_ratelimit_scope_provider_include or test_ratelimit_scope_provider_exclude or test_ratelimit_countby_ipv4 or test_ratelimit_countby_provider or test_ratelimit_countby_company or test_ratelimit_countby_country)' .
            popd

            # Print logs from all services for debug
            # purposes.
            pushd deploy/compose
            docker-compose logs

      - name: Publish Unit Test Results
        # TODO implement https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories
        uses: EnricoMi/publish-unit-test-result-action@ea8720de4a2e723f8204d44fc0178744cf401c1a
        if: always()
        with:
          files: e2e/pytest.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: E2E Test Results on docker-compose
          comment_title: E2E Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
