name: Run e2e tests on docker-compose

on:
  pull_request:
    paths:
      - "deploy/**"
      - "curiefense/**"
      - "e2e/**"
      - ".github/workflows/e2e-compose-tests.yml"

jobs:
  e2e-docker-compose:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure services
        run: |
          echo "BASEDIR=$(git rev-parse --show-toplevel)" >> $GITHUB_ENV
          echo "VERSION=$(git rev-parse --short=12 HEAD)" >> $GITHUB_ENV

          # Deploy all services: istio, curiefense, and echoserver (test app)
          deploy/deploy-ci-compose.sh

      - name: Install dependencies
        run: |
          echo "-- Install curieconfctl --"

          python3 -m venv "${{ env.BASEDIR }}/venv"
          source "${{ env.BASEDIR }}/venv/bin/activate"
          pip install --no-cache-dir -r "${{ env.BASEDIR }}/e2e/requirements.txt"

          pushd "curiefense/curieconf/utils"
            pip install -e .
          popd

          pushd "curiefense/curieconf/client"
            pip install -e .
          popd

      - name: Run tests envoy
        run: |
          echo "-- Run e2e tests for envoy proxy --"
          source "${{ env.BASEDIR }}/venv/bin/activate"
          IP=127.0.0.1
          ENVOY_ENDPOINT="http://$IP:30081"
          LUATESTS_PATH="${{ env.BASEDIR }}/curiefense/curieproxy/rust/luatests"

          pushd e2e
          pytest --log-level INFO -k 'not logging' \
            --base-protected-url $ENVOY_ENDPOINT \
            --base-conf-url http://$IP:30000/api/v3/ \
            --base-ui-url http://$IP:30080 \
            --elasticsearch-url http://$IP:9200/ \
            --luatests-path $LUATESTS_PATH \
            --junit-xml pytest.envoy.xml .
          popd

          echo "-- Run bitflip tests tests --"
          echo "TODO"
          # Here we are not interested in the e2e tests results, almost all
          # of which are expected to fail. We just want to ensure envoy does
          # not crash with malformed requests.
          # A subset of tests is selected to exercise most code paths; not
          # all tests are run to avoid spending more than 5 minutes on this
          # in CI
          pushd e2e
          echo "bit flip tests"
          ENVOY_PID_BEFORE=$(pgrep envoy)
          pytest --log-level INFO \
            --base-protected-url $ENVOY_ENDPOINT \
            --base-conf-url http://$IP:30000/api/v3/ \
            --base-ui-url http://$IP:30080 \
            --elasticsearch-url http://$IP:9200/ \
            --luatests-path $LUATESTS_PATH \
            --flip-requests . || true
          ENVOY_PID_AFTER=$(pgrep envoy)
          if [ "$ENVOY_PID_BEFORE" != "$ENVOY_PID_AFTER" ]; then
            echo "Error: probable envoy crash during bitflip smoke testing"
            exit 1
          fi
          popd

      - name: Run tests nginx
        run: |
          echo "-- Run e2e tests for nginx proxy --"
          source "${{ env.BASEDIR }}/venv/bin/activate"
          IP=127.0.0.1
          NGINX_ENDPOINT="http://$IP:31081"
          LUATESTS_PATH="${{ env.BASEDIR }}/curiefense/curieproxy/rust/luatests"

          pushd e2e
          pytest --log-level INFO \
            --base-protected-url $NGINX_ENDPOINT \
            --base-conf-url http://$IP:30000/api/v3/ \
            --base-ui-url http://$IP:30080 \
            --elasticsearch-url http://$IP:9200/ \
            --luatests-path $LUATESTS_PATH \
            --junit-xml pytest.nginx.xml test_e2e.py::test_logging
          popd

      - name: Dump compose logs
        if: ${{ failure() }}
        run: |
            # Print logs from all services for debug
            # purposes.
            pushd deploy/compose
            docker-compose logs

      - name: Publish Unit Test Results
        # TODO implement https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories
        uses: EnricoMi/publish-unit-test-result-action@ea8720de4a2e723f8204d44fc0178744cf401c1a
        with:
          files: |
            e2e/pytest.envoy.xml
            e2e/pytest.nginx.xml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_name: E2E Test Results on docker-compose
          comment_title: E2E Test Statistics
          hide_comments: all but latest
          comment_on_pr: true
          report_individual_runs: true
          deduplicate_classes_by_file_name: false
        if: >
          always() &&
          github.event.sender.login != 'dependabot[bot]' &&
          ( github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository )

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results
          path: |
            e2e/pytest.envoy.xml
            e2e/pytest.nginx.xml
