name: Manual Retag InfuserBQ Image
on:
  workflow_dispatch:
    inputs:
      BASE_IMAGE_TAG:
        description: 'Tag of base InfuserBQ image:'
        required: true
        default: 'main'
      NEW_IMAGE_TAG:
        description: 'New tag for InfuserBQ image:'
        required: true
        default: 'main'
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up GCP
        uses: google-github-actions/auth@v0.4.3
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          create_credentials_file: true
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Get Date
        id: get-date
        working-directory: ./
        run: |
          DATE=`date +'%Y-%m-%d'`
               echo "::set-output name=DATE::$DATE"
      - name: Set up AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Pull base InfuserBQ Image
        working-directory: ./
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "taskscheduler-infuser-bq"
          BASE_IMAGE_TAG: "${{ github.event.inputs.BASE_IMAGE_TAG }}"
        run: |
          docker pull $REGISTRY/$REPOSITORY:$BASE_IMAGE_TAG
      - name: Retag base InfuserBQ Image
        working-directory: ./
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: "taskscheduler-infuser-bq"
          BASE_IMAGE_TAG: "${{ github.event.inputs.BASE_IMAGE_TAG }}"
        run: |
          docker tag $REGISTRY/$REPOSITORY:$BASE_IMAGE_TAG gcr.io/${{ secrets.GCP_PROJECT_ID }}/taskscheduler-infuser-bq:${{ github.event.inputs.NEW_IMAGE_TAG }}
          docker tag $REGISTRY/$REPOSITORY:$BASE_IMAGE_TAG gcr.io/${{ secrets.GCP_PROJECT_ID }}/taskscheduler-infuser-bq:${{ steps.get-date.outputs.DATE }}-${{ github.sha }}
      - name: Docker push taskscheduler-infuser-bq to gcr
        working-directory: ./
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/taskscheduler-infuser-bq:${{ steps.get-date.outputs.DATE }}-${{ github.sha }}
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/taskscheduler-infuser-bq:${{ github.event.inputs.NEW_IMAGE_TAG }}
      - name: Validate retag
        working-directory: ./
        run: |
          docker image list
      - name: Validate push
        working-directory: ./
        run: |
          gcloud container images list --repository=gcr.io/${{ secrets.GCP_PROJECT_ID }} | grep taskscheduler-infuser-bq
      - name: Clean Up Images
        if: always()
        working-directory: ./
        run: |
          docker system prune --all --force
          docker image list
