name: Run curiefense Rust tests

on:
  pull_request:
    paths:
      - "curiefense/curieproxy/rust/**"
      - ".github/workflows/run-curieconf-rust-tests.yml"

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt

      - name: Run cargo fmt
        working-directory: ./curiefense/curieproxy/rust
        run: 'cargo fmt --all -- --check'

      - name: Run cargo tests
        working-directory: ./curiefense/curieproxy/rust
        run: 'cargo test'

